{{- if .Values.crds.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:{{ .Release.Name }}-crds
  annotations:
    "helm.sh/hook":               "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
    "helm.sh/hook-weight":        "-10"
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-crds
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}:{{ .Release.Name }}-crds
{{- end }}
